name: Build & Test

on:
  push:
    branches-ignore:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.8]

    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn run build
      - name: Check codestyle compliance
        run: yarn run lint
      - name: Run tests
        run: yarn run test
